name: Build Gradle project

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
      - name: See current Version
        run: ./gradlew currentVersion
      - name: Run Axion Release
        run: ./gradlew release
      - name: Push tags
        run: git push --tags